//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketPricingSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class marketpricing : DbContext
    {
        public marketpricing()
            : base("name=marketpricing")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<permission> permissions { get; set; }
        public virtual DbSet<productprice> productprices { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<rolepermission> rolepermissions { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<supermarket> supermarkets { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<message> messages { get; set; }
    
        public virtual ObjectResult<Allproducts_withid_Result> Allproducts_withid()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Allproducts_withid_Result>("Allproducts_withid");
        }
    
        public virtual ObjectResult<Allusers_Result> Allusers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Allusers_Result>("Allusers");
        }
    
        public virtual ObjectResult<Get_Cheapestproduct_Result> Get_Cheapestproduct(Nullable<int> productid)
        {
            var productidParameter = productid.HasValue ?
                new ObjectParameter("productid", productid) :
                new ObjectParameter("productid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Cheapestproduct_Result>("Get_Cheapestproduct", productidParameter);
        }
    
        public virtual ObjectResult<Get_Expensiveproduct_Result> Get_Expensiveproduct(Nullable<int> productid)
        {
            var productidParameter = productid.HasValue ?
                new ObjectParameter("productid", productid) :
                new ObjectParameter("productid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Expensiveproduct_Result>("Get_Expensiveproduct", productidParameter);
        }
    
        public virtual ObjectResult<Marketproducts_Result> Marketproducts(Nullable<int> marketid)
        {
            var marketidParameter = marketid.HasValue ?
                new ObjectParameter("marketid", marketid) :
                new ObjectParameter("marketid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Marketproducts_Result>("Marketproducts", marketidParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Nocategoryid()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Nocategoryid");
        }
    
        public virtual ObjectResult<product_Result> product(Nullable<int> productid)
        {
            var productidParameter = productid.HasValue ?
                new ObjectParameter("productid", productid) :
                new ObjectParameter("productid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<product_Result>("product", productidParameter);
        }
    
        public virtual ObjectResult<ProductList_Result> ProductList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductList_Result>("ProductList");
        }
    
        public virtual ObjectResult<string> Rolepermission(Nullable<int> roleid)
        {
            var roleidParameter = roleid.HasValue ?
                new ObjectParameter("roleid", roleid) :
                new ObjectParameter("roleid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Rolepermission", roleidParameter);
        }
    
        public virtual int updatecategorystatus(Nullable<int> nocategoryid, Nullable<int> categoryid)
        {
            var nocategoryidParameter = nocategoryid.HasValue ?
                new ObjectParameter("nocategoryid", nocategoryid) :
                new ObjectParameter("nocategoryid", typeof(int));
    
            var categoryidParameter = categoryid.HasValue ?
                new ObjectParameter("categoryid", categoryid) :
                new ObjectParameter("categoryid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updatecategorystatus", nocategoryidParameter, categoryidParameter);
        }
    }
}
