//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketPricingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productprice
    {
        public int id { get; set; }
        public int productId { get; set; }
        public int supermarketid { get; set; }
        public int price { get; set; }
        public System.DateTime date { get; set; }
        public int IsActivePrice { get; set; }
    
        public virtual product product { get; set; }
        public virtual supermarket supermarket { get; set; }
    }
}
