//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketPricingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rolepermission
    {
        public int RoleId { get; set; }
        public int PermissionId { get; set; }
        public string nothing { get; set; }
    
        public virtual permission permission { get; set; }
        public virtual role role { get; set; }
    }
}
