//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketPricingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int UserId { get; set; }
        public string Name { get; set; }
        public string phoneNumber { get; set; }
        public string gmail { get; set; }
        public string password { get; set; }
        public int roleid { get; set; }
    
        public virtual role role { get; set; }
    }
}
